Update .zshrc

diff --git a/dot_zshrc b/dot_zshrc
--- a/dot_zshrc
+++ b/dot_zshrc
@@ -70,7 +70,7 @@ ZSH_THEME="robbyrussell"
 # Custom plugins may be added to $ZSH_CUSTOM/plugins/
 # Example format: plugins=(rails git textmate ruby lighthouse)
 # Add wisely, as too many plugins slow down shell startup.
-plugins=(git brew terraform docker kubectl minikube aws colored-man-pages colorize pip python macos zsh-syntax-highlighting poetry)
+plugins=(git cargo rust rustup brew terraform docker kubectl minikube aws colored-man-pages colorize pip python macos zsh-syntax-highlighting poetry)
 
 
 source $ZSH/oh-my-zsh.sh
@@ -111,12 +111,16 @@ alias tf=terraform
 alias g=git
 alias k=kubectl
 
-
 # Spark aliases / exports
 export SPARK_HOME=/opt/homebrew/Cellar/apache-spark/3.3.0/libexec/
 export PYTHONPATH=$SPARK_HOME/python/:$PYTHONP$
 export PATH=$PATH:$HOME/bin
 export PATH=$PATH:$HOME/Library/Python/3.10/bin
+export PATH="/usr/local/opt/ruby/bin:$PATH"
+export PATH="/usr/local/sbin:$PATH"
+export PATH="/usr/local/go/bin:$PATH"
+export PATH="/Applications/Julia-1.8.app/Contents/Resources/julia/bin:$PATH"
+
 
 [[ $commands[kubectl] ]] && source <(kubectl completion zsh)
 
@@ -124,6 +128,41 @@ if [[ -f "$HOME/.cargo/env" ]]
 then
 	source "$HOME/.cargo/env"
 fi
+
+secret () {
+    if [ $# -ne 1 ]; then
+        echo "Usage: secret <filename>"
+        return 1
+    fi
+    if [ ! -f "${1}" ]; then
+        echo "File not found: ${1}"
+        return 1
+    fi
+    output=~/"${1}".$(date +%s).enc
+    if ! gpg --encrypt --armor --output "${output}" -r $KEYID "${1}"; then
+        echo "Encryption failed"
+        return 1
+    fi
+    echo "${1} -> ${output}"
+}
+
+reveal () {
+    if [ $# -ne 1 ]; then
+        echo "Usage: reveal <filename>"
+        return 1
+    fi
+    if [ ! -f "${1}" ]; then
+        echo "File not found: ${1}"
+        return 1
+    fi
+    output=$(echo "${1}" | rev | cut -c16- | rev)
+    if ! gpg --decrypt --output "${output}" "${1}"; then
+        echo "Decryption failed"
+        return 1
+    fi
+    echo "${1} -> ${output}"
+}
+
 
 # Created by `pipx` on 2023-02-08 17:40:05
 export PATH="$PATH:/Users/edejong/.local/bin"
